### ISSUE TITLE
SCregister support

### ISSUE THREAD

**Issue by lnadolski** [ThorstenHellert/SC#1]
Dear Thorsden,

Could you please add  a warning instead of an error if the longitudinal error is not given ?
In other register scripts you set the longitfuinal error to 0 and make a warning.

if any(strcmp(varargin,{'Offset'}))
			offset = varargin{find(strcmp(varargin,{'Offset'}))+1};
			if size(offset,2)~=3 || (size(offset,1)~=1 && size(offset,1)~=2)
				error('Support structure offset uncertainty of ''%s'' must be given as [1x3] (start end endpoints get same offset errors) or [2x3] (start end endpoints get independent offset errors) array.',varargin{1})
			end
		end
		
		if any(strcmp(varargin,{'Roll'}))
			if length(varargin{find(strcmp(varargin,{'Roll'}))+1})~=3
				error('''%s'' roll uncertainty must be [1x3] array [az,ax,ay] of roll (around z-axis), pitch (roll around x-axis) and yaw (roll around y-axis) angle.',varargin{1})
			end
		end

**Comment by ThorstenHellert** [comment]
Done. Thanks for the suggestion! Cheers,

Thorsten
