### ISSUE TITLE
SClocoLib setupLOCOmodel returns RINGData renamed LOCOmodel

### ISSUE THREAD

**Issue by oscarxblanco** [ThorstenHellert/SC#17]
Dear all,

the function library `SClocoLib` uses the name `LOCOmodel` for the LOCO structure `RINGData`.
This is misleading because LOCO uses the same name (in camel case) with a different content.
```
LocoModel = struct('M',[], 'OutlierIndex',[], 'Eta',[], 'EtaOutlierIndex',[], ...
                   'SValues',[], 'SValuesIndex',[], 'ChiSquare',[]);
```

The function `setupLOCOmodel` in `SClocoLib` in fact returns the expected LOCO content of `RINGData`.
```
>> RINGData
RINGData = 
  struct with fields:
     CavityFrequency: 3.5234e+08
    CavityHarmNumber: 416
             Lattice: {3090×1 cell}
```

One posible solution is to rename `LOCOmodel` to `RINGData` in the `SClocoLib` library and the SC documentation.

**Comment by ThorstenHellert** [comment]
Thanks! I have updated the code
