### ISSUE TITLE
SCBBA single corrector

### ISSUE THREAD

**Issue by ZeusMarti** [ThorstenHellert/SC#42]
Hi @ThorstenHellert ,

SCBBA.m makes an orbit bump at each BPM being measured. Would you agree on adding an option to allow for the conventional case just scanning the most effective corrector instead? I can propose it on a branch if you give me some permits!
Cheers,

Z

**Comment by ThorstenHellert** [comment]
Of coarse!

**Comment by ZeusMarti** [comment]
Implemented in #44
